//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmoireV3.Inter {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArmoireV3.Inter.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error adding data: .
        /// </summary>
        internal static string addDataError {
            get {
                return ResourceManager.GetString("addDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alert Sync Error: .
        /// </summary>
        internal static string alertSyncError {
            get {
                return ResourceManager.GetString("alertSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ITEM.
        /// </summary>
        internal static string articleUpCase {
            get {
                return ResourceManager.GetString("articleUpCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LOGOUT.
        /// </summary>
        internal static string buttonDeconnexion {
            get {
                return ResourceManager.GetString("buttonDeconnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum Capacity: .
        /// </summary>
        internal static string capMax {
            get {
                return ResourceManager.GetString("capMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to connect to Database..
        /// </summary>
        internal static string connectDBfail {
            get {
                return ResourceManager.GetString("connectDBfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Credit: .
        /// </summary>
        internal static string credit {
            get {
                return ResourceManager.GetString("credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Currently in the cabinet: .
        /// </summary>
        internal static string curInCab {
            get {
                return ResourceManager.GetString("curInCab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please close the cabinet after removing your selection. Thank you and goodbye..
        /// </summary>
        internal static string cusoon {
            get {
                return ResourceManager.GetString("cusoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database error: .
        /// </summary>
        internal static string dbError {
            get {
                return ResourceManager.GetString("dbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Think to disconnect before leaving !.
        /// </summary>
        internal static string discTip {
            get {
                return ResourceManager.GetString("discTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à door sensor .
        /// </summary>
        internal static string doorSensor {
            get {
                return ResourceManager.GetString("doorSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in article_type.
        /// </summary>
        internal static string errorArticleType {
            get {
                return ResourceManager.GetString("errorArticleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error has occurred:
        ///.
        /// </summary>
        internal static string errorOccurred {
            get {
                return ResourceManager.GetString("errorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please open and close the cabinet to re-evaluate the content, thanks..
        /// </summary>
        internal static string evalContent {
            get {
                return ResourceManager.GetString("evalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synchronization failed.
        /// </summary>
        internal static string failedSync {
            get {
                return ResourceManager.GetString("failedSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Global Sync Error: .
        /// </summary>
        internal static string globalSyncError {
            get {
                return ResourceManager.GetString("globalSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello  .
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inactive user.
        /// </summary>
        internal static string inactiveUser {
            get {
                return ResourceManager.GetString("inactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect login.
        /// </summary>
        internal static string incorLogin {
            get {
                return ResourceManager.GetString("incorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à insertAlert error: .
        /// </summary>
        internal static string insertAlertError {
            get {
                return ResourceManager.GetString("insertAlertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error inserting data: .
        /// </summary>
        internal static string insertDataError {
            get {
                return ResourceManager.GetString("insertDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à insertTagAlert error: .
        /// </summary>
        internal static string insertTagAlertError {
            get {
                return ResourceManager.GetString("insertTagAlertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  intruders.
        /// </summary>
        internal static string intru {
            get {
                return ResourceManager.GetString("intru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LED card error: .
        /// </summary>
        internal static string LEDcardError {
            get {
                return ResourceManager.GetString("LEDcardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load Sync Error: .
        /// </summary>
        internal static string loadSyncError {
            get {
                return ResourceManager.GetString("loadSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à login error: .
        /// </summary>
        internal static string loginError {
            get {
                return ResourceManager.GetString("loginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main Window - Error:.
        /// </summary>
        internal static string mainWinError {
            get {
                return ResourceManager.GetString("mainWinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max :.
        /// </summary>
        internal static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have exceeded your daily quota.
        /// </summary>
        internal static string maxItemToday {
            get {
                return ResourceManager.GetString("maxItemToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MY LOCKER.
        /// </summary>
        internal static string myLocker {
            get {
                return ResourceManager.GetString("myLocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MY SELECTION.
        /// </summary>
        internal static string mySelect {
            get {
                return ResourceManager.GetString("mySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  items in the cabinet, including .
        /// </summary>
        internal static string nbArtCab {
            get {
                return ResourceManager.GetString("nbArtCab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load new map..
        /// </summary>
        internal static string newmap {
            get {
                return ResourceManager.GetString("newmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Badge reader not present.
        /// </summary>
        internal static string noBadgeReader {
            get {
                return ResourceManager.GetString("noBadgeReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LED card not present.
        /// </summary>
        internal static string noLEDcard {
            get {
                return ResourceManager.GetString("noLEDcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No rail.
        /// </summary>
        internal static string noRail {
            get {
                return ResourceManager.GetString("noRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You don&apos;t have enough credits.
        /// </summary>
        internal static string notEnoughCredits {
            get {
                return ResourceManager.GetString("notEnoughCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Item, code.
        /// </summary>
        internal static string notinStock1 {
            get {
                return ResourceManager.GetString("notinStock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  in size .
        /// </summary>
        internal static string notinStock2 {
            get {
                return ResourceManager.GetString("notinStock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  are no longer in stock.
        /// </summary>
        internal static string notinStock3 {
            get {
                return ResourceManager.GetString("notinStock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ongoing service....
        /// </summary>
        internal static string ongoingService {
            get {
                return ResourceManager.GetString("ongoingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cabinet opened since more than 1 minute.
        /// </summary>
        internal static string openCab1minError {
            get {
                return ResourceManager.GetString("openCab1minError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cabinet opened since more than 30 seconds.
        /// </summary>
        internal static string openCab30secError {
            get {
                return ResourceManager.GetString("openCab30secError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operation without refund: .
        /// </summary>
        internal static string opWithoutRef {
            get {
                return ResourceManager.GetString("opWithoutRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Operating without synchro: .
        /// </summary>
        internal static string opWithoutSync {
            get {
                return ResourceManager.GetString("opWithoutSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expiry date exceeded.
        /// </summary>
        internal static string OutofDateUserType {
            get {
                return ResourceManager.GetString("OutofDateUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Out of stock.
        /// </summary>
        internal static string outofstock {
            get {
                return ResourceManager.GetString("outofstock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à POSITION IN THE CABINET.
        /// </summary>
        internal static string posInCab {
            get {
                return ResourceManager.GetString("posInCab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A problem was encountered, please try again later..
        /// </summary>
        internal static string problemTryAgain {
            get {
                return ResourceManager.GetString("problemTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The selected item is temporarily not available in the requested size. 
        ///We offer you exceptionally to select the larger size. 
        ///We thank you for your understanding 
        ///
        ///Do you desire a larger article?.
        /// </summary>
        internal static string propositionSizeSup {
            get {
                return ResourceManager.GetString("propositionSizeSup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantity : .
        /// </summary>
        internal static string quant {
            get {
                return ResourceManager.GetString("quant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reload Sync Error: .
        /// </summary>
        internal static string reloadSyncError {
            get {
                return ResourceManager.GetString("reloadSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To select a larger item,
        ///please log in again after the withdrawal of the selected item.
        /// </summary>
        internal static string reqLargerArticleCondition {
            get {
                return ResourceManager.GetString("reqLargerArticleCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restitution Sync Error: .
        /// </summary>
        internal static string restSyncError {
            get {
                return ResourceManager.GetString("restSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return.
        /// </summary>
        internal static string returnText {
            get {
                return ResourceManager.GetString("returnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RFIDScanRetrait Error: .
        /// </summary>
        internal static string RFIDScanRetraitError {
            get {
                return ResourceManager.GetString("RFIDScanRetraitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error scan: .
        /// </summary>
        internal static string scanError {
            get {
                return ResourceManager.GetString("scanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à seconds remaining..
        /// </summary>
        internal static string secRemain {
            get {
                return ResourceManager.GetString("secRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Now you can select your outfits.
        ///.
        /// </summary>
        internal static string selectOutfit {
            get {
                return ResourceManager.GetString("selectOutfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size : .
        /// </summary>
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SIZE.
        /// </summary>
        internal static string sizeUpCase {
            get {
                return ResourceManager.GetString("sizeUpCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error during synchronization of the cabinet: .
        /// </summary>
        internal static string synchroCabError {
            get {
                return ResourceManager.GetString("synchroCabError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à synchro init error.
        /// </summary>
        internal static string synchroInitError {
            get {
                return ResourceManager.GetString("synchroInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synchro initialization error: .
        /// </summary>
        internal static string syncInitError {
            get {
                return ResourceManager.GetString("syncInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System Error.
        /// </summary>
        internal static string systemError {
            get {
                return ResourceManager.GetString("systemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ERROR.
        /// </summary>
        internal static string textBoxErreur {
            get {
                return ResourceManager.GetString("textBoxErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RFID reader is not connected.
        /// </summary>
        internal static string textBoxErreurImpinj {
            get {
                return ResourceManager.GetString("textBoxErreurImpinj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restitution is not connected.
        /// </summary>
        internal static string textBoxErreurImpinjRestitution {
            get {
                return ResourceManager.GetString("textBoxErreurImpinjRestitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialization, Please wait!.
        /// </summary>
        internal static string textBoxErreurInitialisation {
            get {
                return ResourceManager.GetString("textBoxErreurInitialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BDD Error.
        /// </summary>
        internal static string textBoxErreurLocalBDDAvailable {
            get {
                return ResourceManager.GetString("textBoxErreurLocalBDDAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error RAIL not connected.
        /// </summary>
        internal static string textBoxErreurRailAvailable {
            get {
                return ResourceManager.GetString("textBoxErreurRailAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PLACE YOUR BADGE.
        /// </summary>
        internal static string textBoxInsererBadge {
            get {
                return ResourceManager.GetString("textBoxInsererBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your smart cabinet..
        /// </summary>
        internal static string textBoxMagnetoID {
            get {
                return ResourceManager.GetString("textBoxMagnetoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are .
        /// </summary>
        internal static string thereR {
            get {
                return ResourceManager.GetString("thereR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unhandled error occurred. The program will close. Details:
        ///.
        /// </summary>
        internal static string unhandledErrorOcc {
            get {
                return ResourceManager.GetString("unhandledErrorOcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not update alerts: .
        /// </summary>
        internal static string updateAlertsProblem {
            get {
                return ResourceManager.GetString("updateAlertsProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error updating data: .
        /// </summary>
        internal static string updateDataError {
            get {
                return ResourceManager.GetString("updateDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à updateEpcReload: Tag inexistent.
        /// </summary>
        internal static string updateEpcReloadTagError {
            get {
                return ResourceManager.GetString("updateEpcReloadTagError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à updateEpcRestitution: Tag inexistent.
        /// </summary>
        internal static string updateEpcRestitutionTagError {
            get {
                return ResourceManager.GetString("updateEpcRestitutionTagError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error update.
        /// </summary>
        internal static string updateError {
            get {
                return ResourceManager.GetString("updateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Sync Error: .
        /// </summary>
        internal static string userSyncError {
            get {
                return ResourceManager.GetString("userSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à userTimer sync error: .
        /// </summary>
        internal static string userTimerSyncError {
            get {
                return ResourceManager.GetString("userTimerSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string validate {
            get {
                return ResourceManager.GetString("validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait!!!.
        /// </summary>
        internal static string wait {
            get {
                return ResourceManager.GetString("wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ongoing scan. Please wait ....
        /// </summary>
        internal static string waitDuringScan {
            get {
                return ResourceManager.GetString("waitDuringScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome !.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  and welcome in your space ID box.
        ///.
        /// </summary>
        internal static string welIDbox {
            get {
                return ResourceManager.GetString("welIDbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wrong type of user.
        /// </summary>
        internal static string wrongUserType {
            get {
                return ResourceManager.GetString("wrongUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your order :.
        /// </summary>
        internal static string yourOrder {
            get {
                return ResourceManager.GetString("yourOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à zsyncLoad Error: .
        /// </summary>
        internal static string zsyncLoadError {
            get {
                return ResourceManager.GetString("zsyncLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à zsyncUser Error: .
        /// </summary>
        internal static string zsyncUserError {
            get {
                return ResourceManager.GetString("zsyncUserError", resourceCulture);
            }
        }
    }
}
